// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCehsw5uFQuCHvXL8sCAS5N3huAgmClP4I',
    appId: '1:917242142311:web:3b648f3372c07728d27ec2',
    messagingSenderId: '917242142311',
    projectId: 'chatapp-b83f9',
    authDomain: 'chatapp-b83f9.firebaseapp.com',
    storageBucket: 'chatapp-b83f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN8qQK4Yw2H_T7K22Ur4jizvBaIqTz2Bw',
    appId: '1:917242142311:android:72eccfd93b7b4733d27ec2',
    messagingSenderId: '917242142311',
    projectId: 'chatapp-b83f9',
    storageBucket: 'chatapp-b83f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlFV3K6bJ1KnkExjdSFv_2kbgtNpVSMdU',
    appId: '1:917242142311:ios:efe97ce55f8bcd31d27ec2',
    messagingSenderId: '917242142311',
    projectId: 'chatapp-b83f9',
    storageBucket: 'chatapp-b83f9.appspot.com',
    androidClientId: '917242142311-f9tcirtbmjpp1gem4jfce5mqv7bg3g2d.apps.googleusercontent.com',
    iosClientId: '917242142311-8ild4k0cj94hshaok3ci2olq1qj2gdtr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlFV3K6bJ1KnkExjdSFv_2kbgtNpVSMdU',
    appId: '1:917242142311:ios:efe97ce55f8bcd31d27ec2',
    messagingSenderId: '917242142311',
    projectId: 'chatapp-b83f9',
    storageBucket: 'chatapp-b83f9.appspot.com',
    androidClientId: '917242142311-f9tcirtbmjpp1gem4jfce5mqv7bg3g2d.apps.googleusercontent.com',
    iosClientId: '917242142311-8ild4k0cj94hshaok3ci2olq1qj2gdtr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCehsw5uFQuCHvXL8sCAS5N3huAgmClP4I',
    appId: '1:917242142311:web:72be1af91fdab1add27ec2',
    messagingSenderId: '917242142311',
    projectId: 'chatapp-b83f9',
    authDomain: 'chatapp-b83f9.firebaseapp.com',
    storageBucket: 'chatapp-b83f9.appspot.com',
  );

}